### ISSUE TITLE
V5.1.4.1: UOSL_Error "thisdatasource_has_prescriptions" not found

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#81] opened 2023-11-15 09:10 UTC
Hi @GiorgioLimoncella 
we are  running v5.1.4.1 go this error message from`02_parameters_CDM.R`
@antepharma

**Comment by GiorgioLimoncella** [comment] 2023-11-16 13:11
Hi @jingzhuio, 

the parameter **thisdatasource_has_prescriptions** is created in the step _/p_parameters/01_parameters_program.R_.
Can you please run this step again and double-check that no errors are present? 

Many thank, 
Giorgio

**Comment by jingzh95** [comment] 2023-11-16 14:18
> Hi @jingzhuio,
> 
> the parameter **thisdatasource_has_prescriptions** is created in the step _/p_parameters/01_parameters_program.R_. Can you please run this step again and double-check that no errors are present?
> 
> Many thank, Giorgio

Hi Giorgio, this step works fine. The last line in the console says "This datasource is OSLO"

**Comment by GiorgioLimoncella** [comment] 2023-11-16 17:01
The problem is that the name of the data source in the CDM_SOURCE table was changed.
The parameters were set with _UOSL_ as the name of the data source. Has only the name been changed or is the ETL also different?

**Comment by jingzh95** [comment] 2023-11-16 17:05
Hi Giorgio, it is the same. I think the different parts for ConcePTION data and VAC4EU data I have already changed. 
I tried to continue and it worked now.  Feel free to close the issue.
I'm terribly sorry for the issue. I cannot explain why.

**Comment by GiorgioLimoncella** [comment] 2023-11-16 17:33
Do not worry at all! 
Let me know if there are any other problems

**Closed as completed by GiorgioLimoncella** 2023-11-16 17:33 UTC
