### ISSUE TITLE
Error in step_01_03 (UOSL)

### ISSUE THREAD

**Issue by antepharma** [ARS-toscana/ConcePTIONAlgorithmPregnancies#86] opened 2024-01-02 11:20 UTC
Hi @GiorgioLimoncella  @DanOV , 

It looks like the updated changes with the current version (5.2) on "step_01_03_T2.1_create_conceptset_datasets.R" is creating an Error at UOSL. @SHayati. The previous version used to run without issue at UOSL.

Best, 
Anteneh/UOSL team

![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/113092005/3eb6b70e-ce38-4d02-9a3b-c5a65163b289)

**Comment by DanOV** [comment] 2024-01-02 11:39
Hi,

In our case the new release seems to be working fine for the 01_03 step. We previously had issues with the RAM but seems that it was already solved.

I will let you know once it is completed.

Best,
Dan/SIDIAP team

**Comment by GiorgioLimoncella** [comment] 2024-01-02 17:21
Hi @antepharma, 
Unfortunately, I can't reproduce the error locally, can we have a short call to check together? 

Many thanks!

Giorgio

**Comment by antepharma** [comment] 2024-01-03 08:23
Hi @GiorgioLimoncella, 

Here at UOSL, the error was reproduced both in vac4eu and conception(@SHayati?) dataset separately. Yes, I would like that/to check together. Are you available today afternoon from 13:00? 

Best,
Anteneh/UOSL team

**Comment by SHayati** [comment] 2024-01-03 09:27
Thank you @antepharma. Dear @GiorgioLimoncella, I could not create a code to reproduce the error. We will discuss it in the meeting.

**Comment by GiorgioLimoncella** [comment] 2024-01-08 10:28
@antepharma

The problem is fixed in release 5.2.1

Best, 
Giorgio

**Closed as completed by GiorgioLimoncella** 2024-01-08 10:28 UTC
